// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/base/Card.vue')['default']
    Input: typeof import('./src/components/base/Input.vue')['default']
    Introduction: typeof import('./src/components/home/Introduction.vue')['default']
    PersonalData: typeof import('./src/components/home/PersonalData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/base/Select.vue')['default']
  }
}

export {}
